version: '3.7'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/prod/php.docker
    container_name: "${PROJECT_NAME}_php"
    working_dir: /var/www
    restart: always
    volumes:
      - .:/var/www
    command: php index.php